name: Continuous integration
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  schedule:
    - cron: '0 2 * * *'
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 ]
    steps:
    - name: Checkout Git Source
      uses: actions/checkout@master

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm i

    - name: Continuous integration
      run: npm run test
  macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 8, 9, 10, 11, 12, 13, 14, 15, 16 ]
    steps:
    - name: Checkout Git Source
      uses: actions/checkout@master

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm i

    - name: Continuous integration
      run: npm run test
