name: Continuous integration

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 2

      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        node-version: [ 8.x, 9.x, 10.x, 11.x, 12.x, 13.x, 14.x, 15.x, 16.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3
      if: ${{ matrix.os == 'windows-latest' }}

    - name: Install Dependencies
      run: npm i

    - name: Build C++
      run: npm run build

    - name: Continuous integration
      run: npm run test
