name: Continuous integration

on:
  push:
    branches: [ '**' ]
    tags: v*.*.*
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ${{ matrix.ci-type.os }}

    strategy:
      fail-fast: false
      matrix:
        ci-type: [
          {os: "windows-latest", arch: "x86"},
          {os: "windows-latest", arch: "x64"},
          {os: "macos-latest", arch: "x64"},
          {os: "macos-latest", arch: "arm64"},
          {os: "ubuntu-latest", arch: "x64"},
          {os: "ubuntu-latest", arch: "arm64"},
        ]
        node-version: [ 12, 14, 16, 18 ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      if: ${{ matrix.ci-type.os == 'windows-latest' }}

    - name: Install Dependencies
      run: npm i

    - name: Continuous integration
      run: npm run test

    # - name: Build Binary
    #   run: npm run build-${{ matrix.ci-type.arch }}

    # - name: Package Binary
    #   run: npm run pack-actions-${{ matrix.ci-type.arch }}

    # - name: Drat Release
    #   uses: softprops/action-gh-release@v1
    #   if: startsWith(github.ref, 'refs/tags/')
    #   with:
    #     files: release/**
    #     fail_on_unmatched_files: true
    #     draft: true
